apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcr-deploy
  namespace: pcr-dev
spec:
  selector:
      matchLabels:
        app: pcr-pod
  replicas: 1
  template:
      metadata:
        labels:
          app: pcr-pod
      spec:
        containers:
        - name: pcr-app
          image: ciopocacr.azurecr.io/pcr:v3.0
          imagePullPolicy: IfNotPresent          
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"                      
          ports:
          - containerPort: 80   
        imagePullSecrets:
        - name: pcr-secret
        nodeSelector:
          agentpool: npwin
                